// NIFTY sector index (Yahoo symbol) for each watchlist stock. Stocks not listed have no sector: sector filters let them pass.
const GROUPS = {
  '^NSEBANK': 'HDFCBANK ICICIBANK AXISBANK KOTAKBANK INDUSINDBK FEDERALBNK AUBANK IDFCFIRSTB YESBANK',
  '^CNXPSUBANK': 'SBIN BANKBARODA CANBK PNB UNIONBANK INDIANB BANKINDIA MAHABANK',
  '^CNXFIN': 'BAJFINANCE BAJAJFINSV CHOLAFIN SHRIRAMFIN MUTHOOTFIN HDFCAMC HDFCLIFE SBILIFE ICICIGI SBICARD LICHSGFIN PFC RECLTD IREDA IRFC JIOFIN MFSL LTF M&MFIN ABCAPITAL 360ONE BSE MCX MOTILALOFS TATACAP LICI POLICYBZR ICICIAMC GROWW BAJAJHLDNG',
  '^CNXIT': 'INFY TCS WIPRO HCLTECH TECHM LTM COFORGE MPHASIS PERSISTENT OFSS',
  '^CNXAUTO': 'MARUTI M&M BAJAJ-AUTO EICHERMOT HEROMOTOCO TVSMOTOR ASHOKLEY BOSCHLTD MOTHERSON BHARATFORG EXIDEIND TMPV TMCV MRF HYUNDAI TIINDIA',
  '^CNXPHARMA': 'SUNPHARMA CIPLA DRREDDY DIVISLAB LUPIN AUROPHARMA TORNTPHARM ZYDUSLIFE BIOCON GLENMARK LAURUSLABS MANKIND APOLLOHOSP MAXHEALTH FORTIS',
  '^CNXFMCG': 'HINDUNILVR ITC NESTLEIND BRITANNIA TATACONSUM DABUR MARICO GODREJCP COLPAL VBL UNITDSPR RADICO PATANJALI GODFRYPHLP',
  '^CNXMETAL': 'TATASTEEL JSWSTEEL HINDALCO VEDL JINDALSTEL SAIL NMDC NATIONALUM HINDCOPPER HINDZINC APLAPOLLO',
  '^CNXENERGY': 'RELIANCE ONGC BPCL IOC HINDPETRO GAIL OIL NTPC POWERGRID TATAPOWER ADANIGREEN ADANIPOWER NHPC COALINDIA ADANIENSOL ATGL JSWENERGY NLCINDIA PREMIERENE WAAREEENER SUZLON POWERINDIA',
  '^CNXREALTY': 'DLF GODREJPROP LODHA OBEROIRLTY PRESTIGE PHOENIXLTD'
};
const SECTOR_OF = {};
for (const [idx, syms] of Object.entries(GROUPS)) for (const s of syms.split(' ')) SECTOR_OF[s] = idx;
module.exports = { SECTOR_OF, SECTOR_INDEXES: Object.keys(GROUPS) };
